<?php
?>
<div class="sliderContainer <?= $block->getData('slider_multi_field_class') ?>">
    <div class="slider single-item">
        <?php foreach ($block->getColumns('slider_multi_field_steps') as $column) : ?>
            <div>
                <div class="slidertest">
                    <h1><?= $column->getFirstTitle() ?></h1>
                    <h2><?= $column->getSecondTitle() ?></h2>
                    <p class="tl"><?= $column->getDescription() ?></p>
                    <a href="<?= $column->getButtonUrl() ?>" title="<?= $column->getButton() ?>" tabindex="0"><span><?= $column->getButton() ?></span></a></div>
                <picture>
                    <source media="(min-width: 768px)" srcset="<?= $column->getDesktopThumbnail() ?>">
                    <img src="<?= $column->getMobileThumbnail() ?>" alt="" />
                </picture>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="progressBarContainer">
        <div class="item">
            <span data-slick-index="0" class="progressBar"></span>
        </div>
        <div class="item">
            <span data-slick-index="1" class="progressBar"></span>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {

            $(".slider").slick({
                infinite: true,
                arrows: false,
                dots: false,
                autoplay: false,
                speed: 3000,
                slidesToShow: 1,
                slidesToScroll: 1,
            });

            //ticking machine
            var percentTime;
            var tick;
            var time = .1;
            var progressBarIndex = 0;

            $('.progressBarContainer .progressBar').each(function(index) {
                var progress = "<div class='inProgress inProgress" + index + "'></div>";
                $(this).html(progress);
            });

            function startProgressbar() {
                resetProgressbar();
                percentTime = 0;
                tick = setInterval(interval, 10);
            }

            function interval() {
                if (($('.slider .slick-track div[data-slick-index="' + progressBarIndex + '"]').attr("aria-hidden")) === "true") {
                    progressBarIndex = $('.slider .slick-track div[aria-hidden="false"]').data("slickIndex");
                    startProgressbar();
                } else {
                    percentTime += 1 / (time + 5);
                    $('.inProgress' + progressBarIndex).css({
                        width: percentTime + "%"
                    });
                    if (percentTime >= 100) {
                        $('.single-item').slick('slickNext');
                        progressBarIndex++;
                        if (progressBarIndex > 2) {
                            progressBarIndex = 0;
                        }
                        startProgressbar();
                    }
                }
            }

            function resetProgressbar() {
                $('.inProgress').css({
                    width: 0 + '%'
                });
                clearInterval(tick);
            }
            startProgressbar();
            // End ticking machine

            $('.item').click(function () {
                clearInterval(tick);
                var goToThisIndex = $(this).find("span").data("slickIndex");
                $('.single-item').slick('slickGoTo', goToThisIndex, false);
                startProgressbar();
            });
        });
    });

</script>
